cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'

cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'cyberduck'
cask 'dropbox'
cask 'dash'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'mamp'
cask 'opera'
cask 'processing'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'slate'
cask 'spotify'
cask 'sublime-text'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
